package raft.proto;

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeartBeatRPC.proto

public final class HeartBeatRPC {
  private HeartBeatRPC() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeartBeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 leaderId = 1;</code>
     */
    boolean hasLeaderId();
    /**
     * <code>required int32 leaderId = 1;</code>
     */
    int getLeaderId();

    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    java.util.List<AppendEntriesRPC.LogEntries> 
        getLogEntriesList();
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    AppendEntriesRPC.LogEntries getLogEntries(int index);
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    int getLogEntriesCount();
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    java.util.List<? extends AppendEntriesRPC.LogEntriesOrBuilder> 
        getLogEntriesOrBuilderList();
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    AppendEntriesRPC.LogEntriesOrBuilder getLogEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HeartBeat}
   */
  public static final class HeartBeat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeat)
      HeartBeatOrBuilder {
    // Use HeartBeat.newBuilder() to construct.
    private HeartBeat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeat(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeat defaultInstance;
    public static HeartBeat getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeat getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              leaderId_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                logEntries_ = new java.util.ArrayList<AppendEntriesRPC.LogEntries>();
                mutable_bitField0_ |= 0x00000002;
              }
              logEntries_.add(input.readMessage(AppendEntriesRPC.LogEntries.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          logEntries_ = java.util.Collections.unmodifiableList(logEntries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartBeatRPC.internal_static_HeartBeat_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartBeatRPC.internal_static_HeartBeat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatRPC.HeartBeat.class, HeartBeatRPC.HeartBeat.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeat> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeat>() {
      public HeartBeat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeat(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeat> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int LEADERID_FIELD_NUMBER = 1;
    private int leaderId_;
    /**
     * <code>required int32 leaderId = 1;</code>
     */
    public boolean hasLeaderId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 leaderId = 1;</code>
     */
    public int getLeaderId() {
      return leaderId_;
    }

    public static final int LOGENTRIES_FIELD_NUMBER = 2;
    private java.util.List<AppendEntriesRPC.LogEntries> logEntries_;
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    public java.util.List<AppendEntriesRPC.LogEntries> getLogEntriesList() {
      return logEntries_;
    }
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    public java.util.List<? extends AppendEntriesRPC.LogEntriesOrBuilder> 
        getLogEntriesOrBuilderList() {
      return logEntries_;
    }
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    public int getLogEntriesCount() {
      return logEntries_.size();
    }
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    public AppendEntriesRPC.LogEntries getLogEntries(int index) {
      return logEntries_.get(index);
    }
    /**
     * <code>repeated .LogEntries logEntries = 2;</code>
     */
    public AppendEntriesRPC.LogEntriesOrBuilder getLogEntriesOrBuilder(
        int index) {
      return logEntries_.get(index);
    }

    private void initFields() {
      leaderId_ = 0;
      logEntries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLeaderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLogEntriesCount(); i++) {
        if (!getLogEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, leaderId_);
      }
      for (int i = 0; i < logEntries_.size(); i++) {
        output.writeMessage(2, logEntries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, leaderId_);
      }
      for (int i = 0; i < logEntries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, logEntries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HeartBeatRPC.HeartBeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRPC.HeartBeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HeartBeatRPC.HeartBeat prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeat)
        HeartBeatRPC.HeartBeatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeartBeatRPC.internal_static_HeartBeat_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeartBeatRPC.internal_static_HeartBeat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatRPC.HeartBeat.class, HeartBeatRPC.HeartBeat.Builder.class);
      }

      // Construct using HeartBeatRPC.HeartBeat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        leaderId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (logEntriesBuilder_ == null) {
          logEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          logEntriesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeartBeatRPC.internal_static_HeartBeat_descriptor;
      }

      public HeartBeatRPC.HeartBeat getDefaultInstanceForType() {
        return HeartBeatRPC.HeartBeat.getDefaultInstance();
      }

      public HeartBeatRPC.HeartBeat build() {
        HeartBeatRPC.HeartBeat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeartBeatRPC.HeartBeat buildPartial() {
        HeartBeatRPC.HeartBeat result = new HeartBeatRPC.HeartBeat(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.leaderId_ = leaderId_;
        if (logEntriesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            logEntries_ = java.util.Collections.unmodifiableList(logEntries_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.logEntries_ = logEntries_;
        } else {
          result.logEntries_ = logEntriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatRPC.HeartBeat) {
          return mergeFrom((HeartBeatRPC.HeartBeat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatRPC.HeartBeat other) {
        if (other == HeartBeatRPC.HeartBeat.getDefaultInstance()) return this;
        if (other.hasLeaderId()) {
          setLeaderId(other.getLeaderId());
        }
        if (logEntriesBuilder_ == null) {
          if (!other.logEntries_.isEmpty()) {
            if (logEntries_.isEmpty()) {
              logEntries_ = other.logEntries_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLogEntriesIsMutable();
              logEntries_.addAll(other.logEntries_);
            }
            onChanged();
          }
        } else {
          if (!other.logEntries_.isEmpty()) {
            if (logEntriesBuilder_.isEmpty()) {
              logEntriesBuilder_.dispose();
              logEntriesBuilder_ = null;
              logEntries_ = other.logEntries_;
              bitField0_ = (bitField0_ & ~0x00000002);
              logEntriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLogEntriesFieldBuilder() : null;
            } else {
              logEntriesBuilder_.addAllMessages(other.logEntries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLeaderId()) {
          
          return false;
        }
        for (int i = 0; i < getLogEntriesCount(); i++) {
          if (!getLogEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatRPC.HeartBeat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatRPC.HeartBeat) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int leaderId_ ;
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public boolean hasLeaderId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public int getLeaderId() {
        return leaderId_;
      }
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public Builder setLeaderId(int value) {
        bitField0_ |= 0x00000001;
        leaderId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 leaderId = 1;</code>
       */
      public Builder clearLeaderId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        leaderId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<AppendEntriesRPC.LogEntries> logEntries_ =
        java.util.Collections.emptyList();
      private void ensureLogEntriesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          logEntries_ = new java.util.ArrayList<AppendEntriesRPC.LogEntries>(logEntries_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          AppendEntriesRPC.LogEntries, AppendEntriesRPC.LogEntries.Builder, AppendEntriesRPC.LogEntriesOrBuilder> logEntriesBuilder_;

      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public java.util.List<AppendEntriesRPC.LogEntries> getLogEntriesList() {
        if (logEntriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(logEntries_);
        } else {
          return logEntriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public int getLogEntriesCount() {
        if (logEntriesBuilder_ == null) {
          return logEntries_.size();
        } else {
          return logEntriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public AppendEntriesRPC.LogEntries getLogEntries(int index) {
        if (logEntriesBuilder_ == null) {
          return logEntries_.get(index);
        } else {
          return logEntriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder setLogEntries(
          int index, AppendEntriesRPC.LogEntries value) {
        if (logEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogEntriesIsMutable();
          logEntries_.set(index, value);
          onChanged();
        } else {
          logEntriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder setLogEntries(
          int index, AppendEntriesRPC.LogEntries.Builder builderForValue) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.set(index, builderForValue.build());
          onChanged();
        } else {
          logEntriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder addLogEntries(AppendEntriesRPC.LogEntries value) {
        if (logEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogEntriesIsMutable();
          logEntries_.add(value);
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder addLogEntries(
          int index, AppendEntriesRPC.LogEntries value) {
        if (logEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogEntriesIsMutable();
          logEntries_.add(index, value);
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder addLogEntries(
          AppendEntriesRPC.LogEntries.Builder builderForValue) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.add(builderForValue.build());
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder addLogEntries(
          int index, AppendEntriesRPC.LogEntries.Builder builderForValue) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.add(index, builderForValue.build());
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder addAllLogEntries(
          java.lang.Iterable<? extends AppendEntriesRPC.LogEntries> values) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, logEntries_);
          onChanged();
        } else {
          logEntriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder clearLogEntries() {
        if (logEntriesBuilder_ == null) {
          logEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          logEntriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public Builder removeLogEntries(int index) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.remove(index);
          onChanged();
        } else {
          logEntriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public AppendEntriesRPC.LogEntries.Builder getLogEntriesBuilder(
          int index) {
        return getLogEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public AppendEntriesRPC.LogEntriesOrBuilder getLogEntriesOrBuilder(
          int index) {
        if (logEntriesBuilder_ == null) {
          return logEntries_.get(index);  } else {
          return logEntriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public java.util.List<? extends AppendEntriesRPC.LogEntriesOrBuilder> 
           getLogEntriesOrBuilderList() {
        if (logEntriesBuilder_ != null) {
          return logEntriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(logEntries_);
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public AppendEntriesRPC.LogEntries.Builder addLogEntriesBuilder() {
        return getLogEntriesFieldBuilder().addBuilder(
            AppendEntriesRPC.LogEntries.getDefaultInstance());
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public AppendEntriesRPC.LogEntries.Builder addLogEntriesBuilder(
          int index) {
        return getLogEntriesFieldBuilder().addBuilder(
            index, AppendEntriesRPC.LogEntries.getDefaultInstance());
      }
      /**
       * <code>repeated .LogEntries logEntries = 2;</code>
       */
      public java.util.List<AppendEntriesRPC.LogEntries.Builder> 
           getLogEntriesBuilderList() {
        return getLogEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          AppendEntriesRPC.LogEntries, AppendEntriesRPC.LogEntries.Builder, AppendEntriesRPC.LogEntriesOrBuilder> 
          getLogEntriesFieldBuilder() {
        if (logEntriesBuilder_ == null) {
          logEntriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              AppendEntriesRPC.LogEntries, AppendEntriesRPC.LogEntries.Builder, AppendEntriesRPC.LogEntriesOrBuilder>(
                  logEntries_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          logEntries_ = null;
        }
        return logEntriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeat)
    }

    static {
      defaultInstance = new HeartBeat(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeat)
  }

  public interface HeartBeatResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 nodeId = 1;</code>
     */
    boolean hasNodeId();
    /**
     * <code>required int32 nodeId = 1;</code>
     */
    int getNodeId();

    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    java.util.List<AppendEntriesRPC.LogEntries> 
        getLogEntriesList();
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    AppendEntriesRPC.LogEntries getLogEntries(int index);
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    int getLogEntriesCount();
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    java.util.List<? extends AppendEntriesRPC.LogEntriesOrBuilder> 
        getLogEntriesOrBuilderList();
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    AppendEntriesRPC.LogEntriesOrBuilder getLogEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code HeartBeatResponse}
   */
  public static final class HeartBeatResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeatResponse)
      HeartBeatResponseOrBuilder {
    // Use HeartBeatResponse.newBuilder() to construct.
    private HeartBeatResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatResponse defaultInstance;
    public static HeartBeatResponse getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              nodeId_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                logEntries_ = new java.util.ArrayList<AppendEntriesRPC.LogEntries>();
                mutable_bitField0_ |= 0x00000002;
              }
              logEntries_.add(input.readMessage(AppendEntriesRPC.LogEntries.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          logEntries_ = java.util.Collections.unmodifiableList(logEntries_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartBeatRPC.internal_static_HeartBeatResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatRPC.HeartBeatResponse.class, HeartBeatRPC.HeartBeatResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatResponse> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatResponse>() {
      public HeartBeatResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatResponse> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code HeartBeatResponse.IsAlive}
     */
    public enum IsAlive
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>YES = 1;</code>
       */
      YES(0, 1),
      /**
       * <code>NO = 2;</code>
       */
      NO(1, 2),
      ;

      /**
       * <code>YES = 1;</code>
       */
      public static final int YES_VALUE = 1;
      /**
       * <code>NO = 2;</code>
       */
      public static final int NO_VALUE = 2;


      public final int getNumber() { return value; }

      public static IsAlive valueOf(int value) {
        switch (value) {
          case 1: return YES;
          case 2: return NO;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<IsAlive>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<IsAlive>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<IsAlive>() {
              public IsAlive findValueByNumber(int number) {
                return IsAlive.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return HeartBeatRPC.HeartBeatResponse.getDescriptor().getEnumTypes().get(0);
      }

      private static final IsAlive[] VALUES = values();

      public static IsAlive valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private IsAlive(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:HeartBeatResponse.IsAlive)
    }

    private int bitField0_;
    public static final int NODEID_FIELD_NUMBER = 1;
    private int nodeId_;
    /**
     * <code>required int32 nodeId = 1;</code>
     */
    public boolean hasNodeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 nodeId = 1;</code>
     */
    public int getNodeId() {
      return nodeId_;
    }

    public static final int LOGENTRIES_FIELD_NUMBER = 3;
    private java.util.List<AppendEntriesRPC.LogEntries> logEntries_;
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    public java.util.List<AppendEntriesRPC.LogEntries> getLogEntriesList() {
      return logEntries_;
    }
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    public java.util.List<? extends AppendEntriesRPC.LogEntriesOrBuilder> 
        getLogEntriesOrBuilderList() {
      return logEntries_;
    }
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    public int getLogEntriesCount() {
      return logEntries_.size();
    }
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    public AppendEntriesRPC.LogEntries getLogEntries(int index) {
      return logEntries_.get(index);
    }
    /**
     * <code>repeated .LogEntries logEntries = 3;</code>
     */
    public AppendEntriesRPC.LogEntriesOrBuilder getLogEntriesOrBuilder(
        int index) {
      return logEntries_.get(index);
    }

    private void initFields() {
      nodeId_ = 0;
      logEntries_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasNodeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getLogEntriesCount(); i++) {
        if (!getLogEntries(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, nodeId_);
      }
      for (int i = 0; i < logEntries_.size(); i++) {
        output.writeMessage(3, logEntries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, nodeId_);
      }
      for (int i = 0; i < logEntries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, logEntries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HeartBeatRPC.HeartBeatResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRPC.HeartBeatResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HeartBeatRPC.HeartBeatResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatResponse)
        HeartBeatRPC.HeartBeatResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeartBeatRPC.internal_static_HeartBeatResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatRPC.HeartBeatResponse.class, HeartBeatRPC.HeartBeatResponse.Builder.class);
      }

      // Construct using HeartBeatRPC.HeartBeatResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogEntriesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        nodeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (logEntriesBuilder_ == null) {
          logEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          logEntriesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeartBeatRPC.internal_static_HeartBeatResponse_descriptor;
      }

      public HeartBeatRPC.HeartBeatResponse getDefaultInstanceForType() {
        return HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
      }

      public HeartBeatRPC.HeartBeatResponse build() {
        HeartBeatRPC.HeartBeatResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeartBeatRPC.HeartBeatResponse buildPartial() {
        HeartBeatRPC.HeartBeatResponse result = new HeartBeatRPC.HeartBeatResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.nodeId_ = nodeId_;
        if (logEntriesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            logEntries_ = java.util.Collections.unmodifiableList(logEntries_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.logEntries_ = logEntries_;
        } else {
          result.logEntries_ = logEntriesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatRPC.HeartBeatResponse) {
          return mergeFrom((HeartBeatRPC.HeartBeatResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatRPC.HeartBeatResponse other) {
        if (other == HeartBeatRPC.HeartBeatResponse.getDefaultInstance()) return this;
        if (other.hasNodeId()) {
          setNodeId(other.getNodeId());
        }
        if (logEntriesBuilder_ == null) {
          if (!other.logEntries_.isEmpty()) {
            if (logEntries_.isEmpty()) {
              logEntries_ = other.logEntries_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureLogEntriesIsMutable();
              logEntries_.addAll(other.logEntries_);
            }
            onChanged();
          }
        } else {
          if (!other.logEntries_.isEmpty()) {
            if (logEntriesBuilder_.isEmpty()) {
              logEntriesBuilder_.dispose();
              logEntriesBuilder_ = null;
              logEntries_ = other.logEntries_;
              bitField0_ = (bitField0_ & ~0x00000002);
              logEntriesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLogEntriesFieldBuilder() : null;
            } else {
              logEntriesBuilder_.addAllMessages(other.logEntries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasNodeId()) {
          
          return false;
        }
        for (int i = 0; i < getLogEntriesCount(); i++) {
          if (!getLogEntries(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatRPC.HeartBeatResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatRPC.HeartBeatResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int nodeId_ ;
      /**
       * <code>required int32 nodeId = 1;</code>
       */
      public boolean hasNodeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 nodeId = 1;</code>
       */
      public int getNodeId() {
        return nodeId_;
      }
      /**
       * <code>required int32 nodeId = 1;</code>
       */
      public Builder setNodeId(int value) {
        bitField0_ |= 0x00000001;
        nodeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 nodeId = 1;</code>
       */
      public Builder clearNodeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        nodeId_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<AppendEntriesRPC.LogEntries> logEntries_ =
        java.util.Collections.emptyList();
      private void ensureLogEntriesIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          logEntries_ = new java.util.ArrayList<AppendEntriesRPC.LogEntries>(logEntries_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          AppendEntriesRPC.LogEntries, AppendEntriesRPC.LogEntries.Builder, AppendEntriesRPC.LogEntriesOrBuilder> logEntriesBuilder_;

      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public java.util.List<AppendEntriesRPC.LogEntries> getLogEntriesList() {
        if (logEntriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(logEntries_);
        } else {
          return logEntriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public int getLogEntriesCount() {
        if (logEntriesBuilder_ == null) {
          return logEntries_.size();
        } else {
          return logEntriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public AppendEntriesRPC.LogEntries getLogEntries(int index) {
        if (logEntriesBuilder_ == null) {
          return logEntries_.get(index);
        } else {
          return logEntriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder setLogEntries(
          int index, AppendEntriesRPC.LogEntries value) {
        if (logEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogEntriesIsMutable();
          logEntries_.set(index, value);
          onChanged();
        } else {
          logEntriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder setLogEntries(
          int index, AppendEntriesRPC.LogEntries.Builder builderForValue) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.set(index, builderForValue.build());
          onChanged();
        } else {
          logEntriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder addLogEntries(AppendEntriesRPC.LogEntries value) {
        if (logEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogEntriesIsMutable();
          logEntries_.add(value);
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder addLogEntries(
          int index, AppendEntriesRPC.LogEntries value) {
        if (logEntriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLogEntriesIsMutable();
          logEntries_.add(index, value);
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder addLogEntries(
          AppendEntriesRPC.LogEntries.Builder builderForValue) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.add(builderForValue.build());
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder addLogEntries(
          int index, AppendEntriesRPC.LogEntries.Builder builderForValue) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.add(index, builderForValue.build());
          onChanged();
        } else {
          logEntriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder addAllLogEntries(
          java.lang.Iterable<? extends AppendEntriesRPC.LogEntries> values) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, logEntries_);
          onChanged();
        } else {
          logEntriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder clearLogEntries() {
        if (logEntriesBuilder_ == null) {
          logEntries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          logEntriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public Builder removeLogEntries(int index) {
        if (logEntriesBuilder_ == null) {
          ensureLogEntriesIsMutable();
          logEntries_.remove(index);
          onChanged();
        } else {
          logEntriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public AppendEntriesRPC.LogEntries.Builder getLogEntriesBuilder(
          int index) {
        return getLogEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public AppendEntriesRPC.LogEntriesOrBuilder getLogEntriesOrBuilder(
          int index) {
        if (logEntriesBuilder_ == null) {
          return logEntries_.get(index);  } else {
          return logEntriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public java.util.List<? extends AppendEntriesRPC.LogEntriesOrBuilder> 
           getLogEntriesOrBuilderList() {
        if (logEntriesBuilder_ != null) {
          return logEntriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(logEntries_);
        }
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public AppendEntriesRPC.LogEntries.Builder addLogEntriesBuilder() {
        return getLogEntriesFieldBuilder().addBuilder(
            AppendEntriesRPC.LogEntries.getDefaultInstance());
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public AppendEntriesRPC.LogEntries.Builder addLogEntriesBuilder(
          int index) {
        return getLogEntriesFieldBuilder().addBuilder(
            index, AppendEntriesRPC.LogEntries.getDefaultInstance());
      }
      /**
       * <code>repeated .LogEntries logEntries = 3;</code>
       */
      public java.util.List<AppendEntriesRPC.LogEntries.Builder> 
           getLogEntriesBuilderList() {
        return getLogEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          AppendEntriesRPC.LogEntries, AppendEntriesRPC.LogEntries.Builder, AppendEntriesRPC.LogEntriesOrBuilder> 
          getLogEntriesFieldBuilder() {
        if (logEntriesBuilder_ == null) {
          logEntriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              AppendEntriesRPC.LogEntries, AppendEntriesRPC.LogEntries.Builder, AppendEntriesRPC.LogEntriesOrBuilder>(
                  logEntries_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          logEntries_ = null;
        }
        return logEntriesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatResponse)
    }

    static {
      defaultInstance = new HeartBeatResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeatResponse)
  }

  public interface HeartBeatPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:HeartBeatPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    boolean hasUnixTimestamp();
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    long getUnixTimestamp();

    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    boolean hasHeartbeat();
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    HeartBeatRPC.HeartBeat getHeartbeat();
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder();

    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    boolean hasHeartBeatResponse();
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    HeartBeatRPC.HeartBeatResponse getHeartBeatResponse();
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder();
  }
  /**
   * Protobuf type {@code HeartBeatPacket}
   */
  public static final class HeartBeatPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:HeartBeatPacket)
      HeartBeatPacketOrBuilder {
    // Use HeartBeatPacket.newBuilder() to construct.
    private HeartBeatPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HeartBeatPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HeartBeatPacket defaultInstance;
    public static HeartBeatPacket getDefaultInstance() {
      return defaultInstance;
    }

    public HeartBeatPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HeartBeatPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              unixTimestamp_ = input.readInt64();
              break;
            }
            case 18: {
              HeartBeatRPC.HeartBeat.Builder subBuilder = null;
              if (payloadCase_ == 2) {
                subBuilder = ((HeartBeatRPC.HeartBeat) payload_).toBuilder();
              }
              payload_ = input.readMessage(HeartBeatRPC.HeartBeat.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((HeartBeatRPC.HeartBeat) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 2;
              break;
            }
            case 26: {
              HeartBeatRPC.HeartBeatResponse.Builder subBuilder = null;
              if (payloadCase_ == 3) {
                subBuilder = ((HeartBeatRPC.HeartBeatResponse) payload_).toBuilder();
              }
              payload_ = input.readMessage(HeartBeatRPC.HeartBeatResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((HeartBeatRPC.HeartBeatResponse) payload_);
                payload_ = subBuilder.buildPartial();
              }
              payloadCase_ = 3;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeartBeatRPC.internal_static_HeartBeatPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              HeartBeatRPC.HeartBeatPacket.class, HeartBeatRPC.HeartBeatPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<HeartBeatPacket> PARSER =
        new com.google.protobuf.AbstractParser<HeartBeatPacket>() {
      public HeartBeatPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HeartBeatPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HeartBeatPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    private int payloadCase_ = 0;
    private java.lang.Object payload_;
    public enum PayloadCase
        implements com.google.protobuf.Internal.EnumLite {
      HEARTBEAT(2),
      HEARTBEATRESPONSE(3),
      PAYLOAD_NOT_SET(0);
      private int value = 0;
      private PayloadCase(int value) {
        this.value = value;
      }
      public static PayloadCase valueOf(int value) {
        switch (value) {
          case 2: return HEARTBEAT;
          case 3: return HEARTBEATRESPONSE;
          case 0: return PAYLOAD_NOT_SET;
          default: throw new java.lang.IllegalArgumentException(
            "Value is undefined for this oneof enum.");
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public PayloadCase
    getPayloadCase() {
      return PayloadCase.valueOf(
          payloadCase_);
    }

    public static final int UNIXTIMESTAMP_FIELD_NUMBER = 1;
    private long unixTimestamp_;
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public boolean hasUnixTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 unixTimestamp = 1;</code>
     */
    public long getUnixTimestamp() {
      return unixTimestamp_;
    }

    public static final int HEARTBEAT_FIELD_NUMBER = 2;
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public boolean hasHeartbeat() {
      return payloadCase_ == 2;
    }
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public HeartBeatRPC.HeartBeat getHeartbeat() {
      if (payloadCase_ == 2) {
         return (HeartBeatRPC.HeartBeat) payload_;
      }
      return HeartBeatRPC.HeartBeat.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeat heartbeat = 2;</code>
     */
    public HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder() {
      if (payloadCase_ == 2) {
         return (HeartBeatRPC.HeartBeat) payload_;
      }
      return HeartBeatRPC.HeartBeat.getDefaultInstance();
    }

    public static final int HEARTBEATRESPONSE_FIELD_NUMBER = 3;
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public boolean hasHeartBeatResponse() {
      return payloadCase_ == 3;
    }
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public HeartBeatRPC.HeartBeatResponse getHeartBeatResponse() {
      if (payloadCase_ == 3) {
         return (HeartBeatRPC.HeartBeatResponse) payload_;
      }
      return HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
    }
    /**
     * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
     */
    public HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder() {
      if (payloadCase_ == 3) {
         return (HeartBeatRPC.HeartBeatResponse) payload_;
      }
      return HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
    }

    private void initFields() {
      unixTimestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUnixTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasHeartbeat()) {
        if (!getHeartbeat().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasHeartBeatResponse()) {
        if (!getHeartBeatResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        output.writeMessage(2, (HeartBeatRPC.HeartBeat) payload_);
      }
      if (payloadCase_ == 3) {
        output.writeMessage(3, (HeartBeatRPC.HeartBeatResponse) payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, unixTimestamp_);
      }
      if (payloadCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (HeartBeatRPC.HeartBeat) payload_);
      }
      if (payloadCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (HeartBeatRPC.HeartBeatResponse) payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static HeartBeatRPC.HeartBeatPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static HeartBeatRPC.HeartBeatPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(HeartBeatRPC.HeartBeatPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HeartBeatPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:HeartBeatPacket)
        HeartBeatRPC.HeartBeatPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeartBeatRPC.internal_static_HeartBeatPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                HeartBeatRPC.HeartBeatPacket.class, HeartBeatRPC.HeartBeatPacket.Builder.class);
      }

      // Construct using HeartBeatRPC.HeartBeatPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        unixTimestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        payloadCase_ = 0;
        payload_ = null;
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeartBeatRPC.internal_static_HeartBeatPacket_descriptor;
      }

      public HeartBeatRPC.HeartBeatPacket getDefaultInstanceForType() {
        return HeartBeatRPC.HeartBeatPacket.getDefaultInstance();
      }

      public HeartBeatRPC.HeartBeatPacket build() {
        HeartBeatRPC.HeartBeatPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public HeartBeatRPC.HeartBeatPacket buildPartial() {
        HeartBeatRPC.HeartBeatPacket result = new HeartBeatRPC.HeartBeatPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.unixTimestamp_ = unixTimestamp_;
        if (payloadCase_ == 2) {
          if (heartbeatBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartbeatBuilder_.build();
          }
        }
        if (payloadCase_ == 3) {
          if (heartBeatResponseBuilder_ == null) {
            result.payload_ = payload_;
          } else {
            result.payload_ = heartBeatResponseBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.payloadCase_ = payloadCase_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof HeartBeatRPC.HeartBeatPacket) {
          return mergeFrom((HeartBeatRPC.HeartBeatPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(HeartBeatRPC.HeartBeatPacket other) {
        if (other == HeartBeatRPC.HeartBeatPacket.getDefaultInstance()) return this;
        if (other.hasUnixTimestamp()) {
          setUnixTimestamp(other.getUnixTimestamp());
        }
        switch (other.getPayloadCase()) {
          case HEARTBEAT: {
            mergeHeartbeat(other.getHeartbeat());
            break;
          }
          case HEARTBEATRESPONSE: {
            mergeHeartBeatResponse(other.getHeartBeatResponse());
            break;
          }
          case PAYLOAD_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasUnixTimestamp()) {
          
          return false;
        }
        if (hasHeartbeat()) {
          if (!getHeartbeat().isInitialized()) {
            
            return false;
          }
        }
        if (hasHeartBeatResponse()) {
          if (!getHeartBeatResponse().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        HeartBeatRPC.HeartBeatPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (HeartBeatRPC.HeartBeatPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int payloadCase_ = 0;
      private java.lang.Object payload_;
      public PayloadCase
          getPayloadCase() {
        return PayloadCase.valueOf(
            payloadCase_);
      }

      public Builder clearPayload() {
        payloadCase_ = 0;
        payload_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private long unixTimestamp_ ;
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public boolean hasUnixTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public long getUnixTimestamp() {
        return unixTimestamp_;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder setUnixTimestamp(long value) {
        bitField0_ |= 0x00000001;
        unixTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 unixTimestamp = 1;</code>
       */
      public Builder clearUnixTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unixTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilder<
          HeartBeatRPC.HeartBeat, HeartBeatRPC.HeartBeat.Builder, HeartBeatRPC.HeartBeatOrBuilder> heartbeatBuilder_;
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public boolean hasHeartbeat() {
        return payloadCase_ == 2;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public HeartBeatRPC.HeartBeat getHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2) {
            return (HeartBeatRPC.HeartBeat) payload_;
          }
          return HeartBeatRPC.HeartBeat.getDefaultInstance();
        } else {
          if (payloadCase_ == 2) {
            return heartbeatBuilder_.getMessage();
          }
          return HeartBeatRPC.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(HeartBeatRPC.HeartBeat value) {
        if (heartbeatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder setHeartbeat(
          HeartBeatRPC.HeartBeat.Builder builderForValue) {
        if (heartbeatBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartbeatBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder mergeHeartbeat(HeartBeatRPC.HeartBeat value) {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2 &&
              payload_ != HeartBeatRPC.HeartBeat.getDefaultInstance()) {
            payload_ = HeartBeatRPC.HeartBeat.newBuilder((HeartBeatRPC.HeartBeat) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 2) {
            heartbeatBuilder_.mergeFrom(value);
          }
          heartbeatBuilder_.setMessage(value);
        }
        payloadCase_ = 2;
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public Builder clearHeartbeat() {
        if (heartbeatBuilder_ == null) {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 2) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartbeatBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public HeartBeatRPC.HeartBeat.Builder getHeartbeatBuilder() {
        return getHeartbeatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      public HeartBeatRPC.HeartBeatOrBuilder getHeartbeatOrBuilder() {
        if ((payloadCase_ == 2) && (heartbeatBuilder_ != null)) {
          return heartbeatBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 2) {
            return (HeartBeatRPC.HeartBeat) payload_;
          }
          return HeartBeatRPC.HeartBeat.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeat heartbeat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          HeartBeatRPC.HeartBeat, HeartBeatRPC.HeartBeat.Builder, HeartBeatRPC.HeartBeatOrBuilder> 
          getHeartbeatFieldBuilder() {
        if (heartbeatBuilder_ == null) {
          if (!(payloadCase_ == 2)) {
            payload_ = HeartBeatRPC.HeartBeat.getDefaultInstance();
          }
          heartbeatBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              HeartBeatRPC.HeartBeat, HeartBeatRPC.HeartBeat.Builder, HeartBeatRPC.HeartBeatOrBuilder>(
                  (HeartBeatRPC.HeartBeat) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 2;
        return heartbeatBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilder<
          HeartBeatRPC.HeartBeatResponse, HeartBeatRPC.HeartBeatResponse.Builder, HeartBeatRPC.HeartBeatResponseOrBuilder> heartBeatResponseBuilder_;
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public boolean hasHeartBeatResponse() {
        return payloadCase_ == 3;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public HeartBeatRPC.HeartBeatResponse getHeartBeatResponse() {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            return (HeartBeatRPC.HeartBeatResponse) payload_;
          }
          return HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        } else {
          if (payloadCase_ == 3) {
            return heartBeatResponseBuilder_.getMessage();
          }
          return HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder setHeartBeatResponse(HeartBeatRPC.HeartBeatResponse value) {
        if (heartBeatResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payload_ = value;
          onChanged();
        } else {
          heartBeatResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder setHeartBeatResponse(
          HeartBeatRPC.HeartBeatResponse.Builder builderForValue) {
        if (heartBeatResponseBuilder_ == null) {
          payload_ = builderForValue.build();
          onChanged();
        } else {
          heartBeatResponseBuilder_.setMessage(builderForValue.build());
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder mergeHeartBeatResponse(HeartBeatRPC.HeartBeatResponse value) {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3 &&
              payload_ != HeartBeatRPC.HeartBeatResponse.getDefaultInstance()) {
            payload_ = HeartBeatRPC.HeartBeatResponse.newBuilder((HeartBeatRPC.HeartBeatResponse) payload_)
                .mergeFrom(value).buildPartial();
          } else {
            payload_ = value;
          }
          onChanged();
        } else {
          if (payloadCase_ == 3) {
            heartBeatResponseBuilder_.mergeFrom(value);
          }
          heartBeatResponseBuilder_.setMessage(value);
        }
        payloadCase_ = 3;
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public Builder clearHeartBeatResponse() {
        if (heartBeatResponseBuilder_ == null) {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
            onChanged();
          }
        } else {
          if (payloadCase_ == 3) {
            payloadCase_ = 0;
            payload_ = null;
          }
          heartBeatResponseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public HeartBeatRPC.HeartBeatResponse.Builder getHeartBeatResponseBuilder() {
        return getHeartBeatResponseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      public HeartBeatRPC.HeartBeatResponseOrBuilder getHeartBeatResponseOrBuilder() {
        if ((payloadCase_ == 3) && (heartBeatResponseBuilder_ != null)) {
          return heartBeatResponseBuilder_.getMessageOrBuilder();
        } else {
          if (payloadCase_ == 3) {
            return (HeartBeatRPC.HeartBeatResponse) payload_;
          }
          return HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
        }
      }
      /**
       * <code>optional .HeartBeatResponse heartBeatResponse = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          HeartBeatRPC.HeartBeatResponse, HeartBeatRPC.HeartBeatResponse.Builder, HeartBeatRPC.HeartBeatResponseOrBuilder> 
          getHeartBeatResponseFieldBuilder() {
        if (heartBeatResponseBuilder_ == null) {
          if (!(payloadCase_ == 3)) {
            payload_ = HeartBeatRPC.HeartBeatResponse.getDefaultInstance();
          }
          heartBeatResponseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              HeartBeatRPC.HeartBeatResponse, HeartBeatRPC.HeartBeatResponse.Builder, HeartBeatRPC.HeartBeatResponseOrBuilder>(
                  (HeartBeatRPC.HeartBeatResponse) payload_,
                  getParentForChildren(),
                  isClean());
          payload_ = null;
        }
        payloadCase_ = 3;
        return heartBeatResponseBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:HeartBeatPacket)
    }

    static {
      defaultInstance = new HeartBeatPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HeartBeatPacket)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeat_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeatResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_HeartBeatPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HeartBeatPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022HeartBeatRPC.proto\032\026AppendEntriesRPC.p" +
      "roto\">\n\tHeartBeat\022\020\n\010leaderId\030\001 \002(\005\022\037\n\nl" +
      "ogEntries\030\002 \003(\0132\013.LogEntries\"`\n\021HeartBea" +
      "tResponse\022\016\n\006nodeId\030\001 \002(\005\022\037\n\nlogEntries\030" +
      "\003 \003(\0132\013.LogEntries\"\032\n\007IsAlive\022\007\n\003YES\020\001\022\006" +
      "\n\002NO\020\002\"\205\001\n\017HeartBeatPacket\022\025\n\runixTimest" +
      "amp\030\001 \002(\003\022\037\n\theartbeat\030\002 \001(\0132\n.HeartBeat" +
      "H\000\022/\n\021heartBeatResponse\030\003 \001(\0132\022.HeartBea" +
      "tResponseH\000B\t\n\007payload"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          AppendEntriesRPC.getDescriptor(),
        }, assigner);
    internal_static_HeartBeat_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_HeartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeat_descriptor,
        new java.lang.String[] { "LeaderId", "LogEntries", });
    internal_static_HeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_HeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeatResponse_descriptor,
        new java.lang.String[] { "NodeId", "LogEntries", });
    internal_static_HeartBeatPacket_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_HeartBeatPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_HeartBeatPacket_descriptor,
        new java.lang.String[] { "UnixTimestamp", "Heartbeat", "HeartBeatResponse", "Payload", });
    AppendEntriesRPC.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
